apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nosqlbench-demo.fullname" . }}-workloads
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nosqlbench-demo.labels" . | nindent 4 }}
data:
{{- range $path, $_ := .Files.Glob "workloads/*.yaml" }}
  {{ base $path }}: |-
{{ $.Files.Get $path | indent 4 }}
{{- end }}
