apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nosqlbench-demo.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nosqlbench-demo.labels" . | nindent 4 }}
data:
  # Application configuration
  app-config.yaml: |
    databases:
      {{- if .Values.databases.cassandra.enabled }}
      cassandra:
        enabled: true
        host: {{ .Values.databases.cassandra.host | quote }}
        port: {{ .Values.databases.cassandra.port }}
        localdc: {{ .Values.databases.cassandra.localdc | quote }}
        {{- if .Values.databases.cassandra.username }}
        username: {{ .Values.databases.cassandra.username | quote }}
        {{- end }}
      {{- else }}
      cassandra:
        enabled: false
      {{- end }}
      
      {{- if .Values.databases.opensearch.enabled }}
      opensearch:
        enabled: true
        host: {{ .Values.databases.opensearch.host | quote }}
        port: {{ .Values.databases.opensearch.port }}
        {{- if .Values.databases.opensearch.username }}
        username: {{ .Values.databases.opensearch.username | quote }}
        {{- end }}
      {{- else }}
      opensearch:
        enabled: false
      {{- end }}
      
      {{- if .Values.databases.presto.enabled }}
      presto:
        enabled: true
        host: {{ .Values.databases.presto.host | quote }}
        port: {{ .Values.databases.presto.port }}
        user: {{ .Values.databases.presto.user | quote }}
        catalog: {{ .Values.databases.presto.catalog | quote }}
      {{- else }}
      presto:
        enabled: false
      {{- end }}
    
    metrics:
      endpoint: {{ .Values.metrics.endpoint | quote }}
    
    workloads:
      defaultCycleRate: {{ .Values.workloads.defaultCycleRate }}
      threadsAuto: {{ .Values.workloads.threadsAuto }}
      errorsMode: {{ .Values.workloads.errorsMode | quote }}
    
    autoSetup: {{ .Values.webapp.autoSetup }}
    
    # Available workloads based on enabled databases
    availableWorkloads: {{ include "nosqlbench-demo.availableWorkloads" . | quote }}

  # Workload definitions (matching the Flask app config)
  workload-definitions.yaml: |
    workloads:
      {{- range $workloadName, $workloadConfig := .Values.workloadDefinitions }}
      {{ $workloadName }}:
        file: {{ $workloadConfig.file | quote }}
        setup_phases:
          {{- range $workloadConfig.setup_phases }}
          - {{ . | quote }}
          {{- end }}
        run_phase: {{ $workloadConfig.run_phase | quote }}
        driver: {{ $workloadConfig.driver | quote }}
        {{- if $workloadConfig.keyspace }}
        keyspace: {{ $workloadConfig.keyspace | quote }}
        {{- end }}
        enabled: {{- if eq $workloadConfig.driver "cql" }} {{ $.Values.databases.cassandra.enabled }}
        {{- else if eq $workloadConfig.driver "opensearch" }} {{ $.Values.databases.opensearch.enabled }}
        {{- else if eq $workloadConfig.driver "jdbc" }} {{ $.Values.databases.presto.enabled }}
        {{- else }} false
        {{- end }}
      {{- end }}
