apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nosqlbench-demo.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nosqlbench-demo.labels" . | nindent 4 }}
data:
  # Application configuration
  app-config.yaml: |
    # Database endpoints are configured dynamically through the web UI
    # No static database configuration needed

    metrics:
      endpoint: {{ .Values.metrics.endpoint | quote }}
    
    workloads:
      defaultCycleRate: {{ .Values.workloads.defaultCycleRate }}
      threadsAuto: {{ .Values.workloads.threadsAuto }}
      errorsMode: {{ .Values.workloads.errorsMode | quote }}
    
    autoSetup: {{ .Values.webapp.autoSetup }}

    # All workloads are available - database configuration is dynamic
    availableWorkloads: "all"

  # Workload definitions (matching the Flask app config)
  workload-definitions.yaml: |
    workloads:
      {{- range $workloadName, $workloadConfig := .Values.workloadDefinitions }}
      {{ $workloadName }}:
        file: {{ $workloadConfig.file | quote }}
        setup_phases:
          {{- range $workloadConfig.setup_phases }}
          - {{ . | quote }}
          {{- end }}
        run_phase: {{ $workloadConfig.run_phase | quote }}
        driver: {{ $workloadConfig.driver | quote }}
        {{- if $workloadConfig.keyspace }}
        keyspace: {{ $workloadConfig.keyspace | quote }}
        {{- end }}
        enabled: true  # All workloads available - database configuration is dynamic
      {{- end }}
