{{/*
This template is used by the web application to create setup jobs dynamically.
It's not deployed directly but serves as a reference for the job specifications.
*/}}

{{- if .Values.webapp.autoSetup }}
{{- range $workload, $config := .Values.workloadDefinitions }}
{{- $enabled := false }}
{{- if eq $config.driver "cql" }}
  {{- $enabled = $.Values.databases.cassandra.enabled }}
{{- else if eq $config.driver "opensearch" }}
  {{- $enabled = $.Values.databases.opensearch.enabled }}
{{- else if eq $config.driver "jdbc" }}
  {{- $enabled = $.Values.databases.presto.enabled }}
{{- end }}
{{- if $enabled }}
{{- range $phase := $config.setup_phases }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "nosqlbench-demo.fullname" $ }}-setup-{{ $workload | replace "_" "-" }}-{{ $phase | replace "." "-" | replace "_" "-" }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "nosqlbench-demo.labels" $ | nindent 4 }}
    app.kubernetes.io/component: nosqlbench
    job-type: setup
    workload: {{ $workload }}
    phase: {{ $phase | replace "." "-" | replace "_" "-" }}
spec:
  ttlSecondsAfterFinished: {{ $.Values.nosqlbench.jobs.ttlSecondsAfterFinished }}
  backoffLimit: {{ $.Values.nosqlbench.jobs.backoffLimit }}
  template:
    metadata:
      labels:
        {{- include "nosqlbench-demo.selectorLabels" $ | nindent 8 }}
        app.kubernetes.io/component: nosqlbench
        job-type: setup
        workload: {{ $workload }}
    spec:
      restartPolicy: {{ $.Values.nosqlbench.jobs.restartPolicy }}
      {{- with $.Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml $.Values.podSecurityContext | nindent 8 }}
      containers:
        - name: nosqlbench
          securityContext:
            runAsNonRoot: {{ $.Values.securityContext.runAsNonRoot | default true }}
            {{- if $.Values.securityContext.runAsUser }}
            runAsUser: {{ $.Values.securityContext.runAsUser }}
            {{- end }}
            {{- if $.Values.securityContext.runAsGroup }}
            runAsGroup: {{ $.Values.securityContext.runAsGroup }}
            {{- end }}
          image: {{ include "nosqlbench-demo.nosqlbench.image" $ }}
          imagePullPolicy: {{ $.Values.nosqlbench.image.pullPolicy }}
          args:
            - "--include=/workloads"
            - {{ $config.file | quote }}
            - {{ $phase | quote }}
            {{- if eq $config.driver "cql" }}
            - "driver=cql"
            - "host={{ $.Values.databases.cassandra.host }}"
            - "port={{ $.Values.databases.cassandra.port }}"
            - "localdc={{ $.Values.databases.cassandra.localdc }}"
            {{- if $config.keyspace }}
            - "keyspace={{ $config.keyspace }}"
            {{- end }}
            {{- else if eq $config.driver "opensearch" }}
            - "driver=opensearch"
            - "host={{ $.Values.databases.opensearch.host }}"
            - "port={{ $.Values.databases.opensearch.port }}"
            {{- else if eq $config.driver "jdbc" }}
            - "dburl=jdbc:presto://{{ $.Values.databases.presto.host }}:{{ $.Values.databases.presto.port }}/{{ $.Values.databases.presto.catalog }}?user={{ $.Values.databases.presto.user }}"
            - "use_hikaricp=true"
            {{- end }}
            - "threads=auto"
            - "errors={{ $.Values.workloads.errorsMode }}"
          env:
            {{- include "nosqlbench-demo.databaseEnv" $ | nindent 12 }}
          volumeMounts:
            - name: workloads
              mountPath: /workloads
              readOnly: true
          resources:
            {{- toYaml $.Values.nosqlbench.resources | nindent 12 }}
      volumes:
        - name: workloads
          configMap:
            name: {{ include "nosqlbench-demo.fullname" $ }}-workloads
      {{- with $.Values.nosqlbench.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.nosqlbench.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.nosqlbench.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
