# Default values for nosqlbench-demo
# This is a YAML-formatted file.

# Global settings
global:
  # Image registry settings
  imageRegistry: ""
  imagePullSecrets: []

# Database endpoints are configured through the web UI
# No static database configuration needed in values.yaml

# VictoriaMetrics endpoint for metrics collection
metrics:
  endpoint: "http://victoriametrics.monitoring.svc.cluster.local:8428"

# Web application configuration
webapp:
  # Container image settings
  image:
    registry: ""
    repository: "mikeyaacoubstax/mike-personal"
    tag: "latest"
    pullPolicy: IfNotPresent
  
  # Resource limits and requests
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  
  # Service configuration
  service:
    type: ClusterIP
    port: 80
    targetPort: 5000
    annotations: {}
  
  # Ingress configuration
  ingress:
    enabled: false
    className: ""
    annotations: {}
    hosts:
      - host: nosqlbench-demo.local
        paths:
          - path: /
            pathType: Prefix
    tls: []
  
  # Environment variables
  env:
    FLASK_DEBUG: "false"
    SECRET_KEY: "change-me-in-production"
  
  # Auto-setup configuration (disabled - databases configured through UI)
  autoSetup: false
  
  # Node selector and tolerations
  nodeSelector: {}
  tolerations: []
  affinity: {}

# NoSQLBench job configuration
nosqlbench:
  # Container image settings
  image:
    registry: ""
    repository: "nosqlbench/nosqlbench"
    tag: "5.21.8-preview"
    pullPolicy: IfNotPresent
  
  # Default resource limits for jobs
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 256Mi
  
  # Job settings
  jobs:
    # Time to live for completed jobs (in seconds)
    ttlSecondsAfterFinished: 3600
    # Restart policy for jobs
    restartPolicy: Never
    # Backoff limit for failed jobs
    backoffLimit: 3
  
  # Node selector and tolerations for jobs
  nodeSelector: {}
  tolerations: []
  affinity: {}

# RBAC configuration
rbac:
  # Create RBAC resources
  create: true
  # Annotations for service account
  serviceAccountAnnotations: {}

# Security context
securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

# Workload configurations (will be mounted as ConfigMap)
workloads:
  # Default cycle rates for workloads
  defaultCycleRate: 10
  # Default thread configuration
  threadsAuto: true
  # Error handling mode
  errorsMode: "count"

# Individual workload definitions
workloadDefinitions:
  sai_longrun:
    file: "sai_longrun.yaml"
    setup_phases: ["setup.schema", "setup.rampup"]
    run_phase: "sai_reads_test.sai_reads"
    driver: "cql"
    keyspace: "sai_test"
    enabled: false  # Will be set to true if cassandra is enabled

  lwt_longrun:
    file: "lwt_longrun.yaml"
    setup_phases: ["setup.schema", "setup.truncating", "setup.sharding", "setup.lwt_load"]
    run_phase: "lwt-updates.lwt_live_update"
    driver: "cql"
    keyspace: "lwt_ks"
    enabled: false  # Will be set to true if cassandra is enabled

  opensearch_basic_longrun:
    file: "opensearch_basic_longrun.yaml"
    setup_phases: ["default.pre_cleanup", "default.schema", "default.rampup"]
    run_phase: "default.search"
    driver: "opensearch"
    enabled: false  # Will be set to true if opensearch is enabled

  opensearch_vector_search_longrun:
    file: "opensearch_vector_search_longrun.yaml"
    setup_phases: ["default.pre_cleanup", "default.schema", "default.rampup"]
    run_phase: "default.search"
    driver: "opensearch"
    enabled: false  # Will be set to true if opensearch is enabled

  opensearch_bulk_longrun:
    file: "opensearch_bulk_longrun.yaml"
    setup_phases: ["default.pre_cleanup", "default.schema", "default.bulk_load"]
    run_phase: "default.verify"
    driver: "opensearch"
    enabled: false  # Will be set to true if opensearch is enabled

  jdbc_analytics_longrun:
    file: "jdbc_analytics_longrun.yaml"
    setup_phases: ["default.drop", "default.schema", "default.rampup"]
    run_phase: "default.analytics"
    driver: "jdbc"
    enabled: false  # Will be set to true if presto is enabled

  jdbc_ecommerce_longrun:
    file: "jdbc_ecommerce_longrun.yaml"
    setup_phases: ["default.drop", "default.schema", "default.rampup"]
    run_phase: "default.transactions"
    driver: "jdbc"
    enabled: false  # Will be set to true if presto is enabled

# Persistence for logs and results
persistence:
  enabled: false
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 10Gi
  annotations: {}

# Pod disruption budget
podDisruptionBudget:
  enabled: false
  minAvailable: 1
  # maxUnavailable: 1

# Monitoring and observability
monitoring:
  # Enable ServiceMonitor for Prometheus
  serviceMonitor:
    enabled: false
    namespace: ""
    labels: {}
    annotations: {}
    interval: 30s
    scrapeTimeout: 10s

# Network policies
networkPolicy:
  enabled: false
  ingress: []
  egress: []
